# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d49ec7d9f7d26cfcdc7e30f17b043a17e4ea3a2d745e267cce5157fc5a3dff082cdf7fbfe7160930421bb764c0cadf31406d50aeafd9f4cf148a33e64b1a8638

test:
  secret_key_base: d7fcf93166dbe5bd02a60c5e341375cc0fe5f9d5cb8140c110f717c071c61ff273a501e2b15b59629f1c81b1243b60ed9b776213a5a8c13900386fe8d750ba16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
